### ISSUE TITLE
Add (transitive) group actions?

### ISSUE THREAD

**Issue by turion** [Taneb/groups#15]
Would you accept a PR that adds group actions, and transitive group actions, based on (or inspired by) https://hackage.haskell.org/package/monoid-extras-0.6.1/docs/Data-Monoid-Action.html?

**Comment by Taneb** [comment]
I feel like this should go in `monoid-extras`. That library already depends on this one, and it would mean there could be a subclass constraint `Action m s => TransitiveAction m s` or whatever the class gets called.

**Comment by turion** [comment]
Makes a lot of sense, thanks!
