### ISSUE TITLE
Should the superclass for `Abelian` be `Semigroup`?

### ISSUE THREAD

**Issue by endgame** [Taneb/groups#4]
I note that in the `patch` library, the typeclass for additive (i.e., commutative/abelian) binary operations is defined as `class Semigroup g => Additive g`: https://github.com/reflex-frp/patch/blob/946fae73563bd1c14c6bd56db3424a97cf1285b6/src/Data/Patch.hs#L49

In `groups`, the equivalent class has a `Group` superclass: `class Group g => Abelian g`. I feel like relaxing this constraint is probably backwards-compatible, and I could CPP it so that we have `class Monoid g => Abelian g` on GHC versions that lack `class Semigroup` in `base` (or should we conditionally depend on `semigroups`?).

(The term "Abelian Semigroup" appears to be valid but uncommon, so we could add an alias `type Additive = Abelian` if that's useful?)

CC @Ericson2314 who seems to have the most to do with `patch`.

**Comment by Taneb** [comment]
If it does have `Semigroup` or `Monoid` rather than `Group` as its superclass, then it doesn't belong in this library, but rather somewhere else like `monoid-extras` or maybe even `base.
