### ISSUE TITLE
Provide changelog?

### ISSUE THREAD

**Issue by Bodigrim** [Taneb/groups#9]
Otherwise I have no idea whether it is safe to relax `groups < 0.5` bound or not.

**Comment by Taneb** [comment]
I'm on holiday right now. I'll figure one out when I'm back

**Comment by Bodigrim** [comment]
@Taneb just a gentle reminder about changelog. `@since` pragmas would be much appreciated as well.

**Comment by Taneb** [comment]
Ooops, sorry! Thanks for the reminder

**Comment by Ericson2314** [comment]
I am working on this.
